---
- name: Ensure docker compose requirements are provided
  ansible.builtin.assert:
    that:
      - xray_domain | length > 0
    fail_msg: "xray_domain must be provided before rendering docker-compose.yml."

- name: Ensure compose directory exists
  ansible.builtin.file:
    path: "{{ compose_project_directory }}"
    state: directory
    mode: "0750"

- name: Render Docker Compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ compose_project_directory }}/docker-compose.yml"
    mode: "0640"
  notify: Restart xray container

- name: Run docker compose up
  ansible.builtin.command: docker compose up -d
  args:
    chdir: "{{ compose_project_directory }}"
  when:
    - docker_compose_up | bool
    - not ansible_check_mode
  register: compose_up
  changed_when: compose_up.rc == 0

- name: Validate Xray container stability attempt {{ item }}
  ansible.builtin.shell: |
    sleep {{ xray_stability_check_delay }}
    docker inspect -f '{{ '{{' }} .State.Status {{ '}}' }}' {{ xray_container_name }}
  args:
    executable: /bin/bash
  register: xray_stability_check
  loop: "{{ range(1, xray_stability_check_count + 1) | list }}"
  loop_control:
    label: "attempt {{ item }}"
  changed_when: false
  failed_when:
    - xray_stability_check.rc != 0
    - xray_stability_check.stdout is not defined or (xray_stability_check.stdout | trim) == ''
    - (xray_stability_check.stdout | trim | lower) != 'running'
  when:
    - docker_compose_up | bool
    - not ansible_check_mode
